# Generated by Django 6.0.2 on 2026-02-10 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('number', models.IntegerField(max_length=5)),
                ('account_type', models.CharField(choices=[('AS', 'Asset'), ('LI', 'Liability'), ('EQ', 'Equity'), ('IN', 'Income'), ('EX', 'Expenses')])),
                ('description', models.CharField(max_length=250)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneypyle.account')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
