# Generated by Django 6.0.2 on 2026-02-10 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypyle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moneypyle.account'),
        ),
    ]
