# Generated by Django 6.0.2 on 2026-02-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypyle', '0002_alter_account_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent_id',
            field=models.IntegerField(),
        ),
    ]
