# Generated by Django 6.0.2 on 2026-02-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneypyle', '0003_alter_account_number_alter_account_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='parent_id',
        ),
    ]
