# Generated by Django 6.0.2 on 2026-02-11 16:54

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypyle', '0004_remove_account_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField()),
                ('state', models.CharField(choices=[('OH', 'Ohio')])),
                ('zip', models.IntegerField(max_length=5)),
                ('country', models.CharField()),
                ('company_name', models.CharField()),
                ('description', models.CharField(blank=True)),
                ('industry', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('type', models.CharField(blank=True)),
                ('product_description', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(blank=True, null=True)),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('full_name', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat('first_name', models.Value(' '), 'last_name'), output_field=models.CharField(max_length=64))),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company_id', models.ManyToManyField(blank=True, related_name='Party', to='moneypyle.company')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_date', models.DateField()),
                ('reference_number', models.CharField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('memo', models.CharField(blank=True, max_length=256)),
                ('party_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moneypyle.party')),
            ],
        ),
    ]
