# Generated by Django 6.0.2 on 2026-02-11 17:18

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypyle', '0005_company_product_transactionline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionline',
            name='account_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='moneypyle.account'),
        ),
        migrations.AddField(
            model_name='transactionline',
            name='line_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionline',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='moneypyle.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionline',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionline',
            name='rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionline',
            name='transaction_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='moneypyle.transaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionline',
            name='transaction_description',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='zip',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='transactionline',
            name='line_total',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('rate')), output_field=models.DecimalField(decimal_places=2, max_digits=10)),
        ),
    ]
