# Generated by Django 6.0.2 on 2026-02-11 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypyle', '0006_transactionline_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionline',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moneypyle.account'),
        ),
    ]
