# Generated by Django 6.0.2 on 2026-02-11 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypyle', '0007_alter_transactionline_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('debit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('memo', models.CharField()),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_account', to='moneypyle.account')),
                ('credit_party', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_party', to='moneypyle.party')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_account', to='moneypyle.account')),
                ('debit_party', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_party', to='moneypyle.party')),
            ],
        ),
    ]
