# Generated by Django 6.0.2 on 2026-02-11 20:40

import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypyle', '0008_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionline',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='transactionline',
            name='product_id',
        ),
        migrations.AddField(
            model_name='transactionline',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='transactionline',
            name='debit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_description', models.CharField(blank=True)),
                ('quantity', models.IntegerField()),
                ('rate', models.FloatField()),
                ('line_total', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('rate')), output_field=models.DecimalField(decimal_places=2, max_digits=10))),
                ('line_number', models.IntegerField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moneypyle.account')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moneypyle.product')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moneypyle.transaction')),
            ],
        ),
        migrations.RemoveField(
            model_name='transactionline',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='transactionline',
            name='rate',
        ),
    ]
