# Generated by Django 6.0.2 on 2026-02-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneypyle', '0009_remove_transactionline_line_total_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionLine',
            new_name='AccountEntry',
        ),
    ]
