# Generated by Django 6.0.2 on 2026-02-14 03:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypyle', '0010_rename_transactionline_accountentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountentry',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='accountentry',
            old_name='transaction_id',
            new_name='transaction',
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='debit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Debit'),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='transaction_description',
            field=models.CharField(blank=True, verbose_name='Description'),
        ),
    ]
