# Generated by Django 6.0.2 on 2026-02-21 15:49

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypyle', '0013_company_is_active_party_is_active_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='full_name',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat('first_name', models.Value(' '), 'last_name'), output_field=models.CharField(max_length=64), unique=True),
        ),
    ]
