# Generated by Django 6.0.2 on 2026-02-21 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypyle', '0014_alter_party_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='party_id',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='moneypyle.party'),
        ),
    ]
